// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUwm_rrqh1070Cxhe0rj_7oY2AzSr9FuM',
    appId: '1:279930632379:web:7037d2fb2c8e269614119e',
    messagingSenderId: '279930632379',
    projectId: 'task-2-devstack',
    authDomain: 'task-2-devstack.firebaseapp.com',
    storageBucket: 'task-2-devstack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZAD4gKwJsKnCUbNxwFYexIQIJ9c2qZU4',
    appId: '1:279930632379:android:861cb0b96004c50714119e',
    messagingSenderId: '279930632379',
    projectId: 'task-2-devstack',
    storageBucket: 'task-2-devstack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2himYtOSCjo-cWSwtiDMJXhSmbf7mjQ',
    appId: '1:279930632379:ios:54189975055d49eb14119e',
    messagingSenderId: '279930632379',
    projectId: 'task-2-devstack',
    storageBucket: 'task-2-devstack.appspot.com',
    iosClientId: '279930632379-gjknvgapv33ts5geqd3n8j922qsl3bi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd2himYtOSCjo-cWSwtiDMJXhSmbf7mjQ',
    appId: '1:279930632379:ios:54189975055d49eb14119e',
    messagingSenderId: '279930632379',
    projectId: 'task-2-devstack',
    storageBucket: 'task-2-devstack.appspot.com',
    iosClientId: '279930632379-gjknvgapv33ts5geqd3n8j922qsl3bi4.apps.googleusercontent.com',
    iosBundleId: 'com.example.task2',
  );
}
